DROP DATABASE IF EXISTS datahare;
DROP DATABASE IF EXISTS datashare_liquibase;
DROP DATABASE IF EXISTS dstest;
DROP DATABASE IF EXISTS test;
CREATE DATABASE datahare;
CREATE DATABASE datashare_liquibase;
CREATE DATABASE dstest;
CREATE DATABASE test;
GRANT ALL PRIVILEGES ON DATABASE datashare TO dstest;
GRANT ALL PRIVILEGES ON DATABASE datashare_liquibase TO dstest;
GRANT ALL PRIVILEGES ON DATABASE dstest TO dstest;
GRANT ALL PRIVILEGES ON DATABASE test TO dstest;

